# Generated by Django 4.1.7 on 2023-11-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0014_task_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='right_answer',
            field=models.CharField(default=1, max_length=128, verbose_name='Верный ответ'),
        ),
    ]
