# Generated by Django 4.1.7 on 2023-11-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0015_alter_task_right_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points_task',
        ),
    ]
